-- Create contact_submissions table
create table contact_submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    phone text not null,
    email text,
    service text not null,
    message text
);

-- Enable Row Level Security (RLS)
alter table contact_submissions enable row level security;

-- Create policy for inserting submissions (public can insert)
create policy "Allow public to insert contact submissions"
on contact_submissions
for insert
with check (true);

-- Create policy for selecting submissions (only authenticated service_role can select)
create policy "Allow service_role to select contact submissions"
on contact_submissions
for select
using (true);